#!/usr/bin/env python3
"""Generate the root index.html listing every tool in this repo.

Scans top-level directories for a `tool.json` file and renders a static
index page. No dependencies beyond the Python 3 standard library.

Usage: python3 build.py
"""

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "index.html"

TEMPLATE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>tools</title>
<meta name="description" content="An assortment of small HTML+JavaScript tools.">
<style>
  :root {{
    --bg:#fefefe; --surface:#ffffff; --ink:#0b0b0b; --ink-soft:#5a5866;
    --hairline:#e6e4de; --accent:#5541EA; --accent-soft:rgba(85,65,234,.07);
    --mono:ui-monospace,"SF Mono","JetBrains Mono",Menlo,Consolas,monospace;
    --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,"Helvetica Neue",Arial,sans-serif;
  }}
  * {{ box-sizing:border-box; margin:0; padding:0 }}
  body {{ background:var(--bg); color:var(--ink); font-family:var(--sans); font-size:14px; line-height:1.5 }}
  header {{
    position:sticky; top:0; z-index:10; display:flex; align-items:center; justify-content:space-between;
    gap:16px; padding:14px 24px; border-bottom:1px solid var(--hairline); background:var(--surface);
  }}
  header h1 {{ font-size:15px; font-weight:650; letter-spacing:.02em }}
  header .count {{ font-family:var(--mono); font-size:10px; letter-spacing:.14em; text-transform:uppercase; color:var(--ink-soft) }}
  #search {{
    font:inherit; padding:6px 10px; border:1px solid var(--hairline); border-radius:6px;
    min-width:220px; background:var(--bg); color:var(--ink);
  }}
  #search:focus {{ outline:none; border-color:var(--accent) }}
  main {{ max-width:720px; margin:0 auto; padding:24px }}
  .intro {{ color:var(--ink-soft); margin-bottom:16px }}
  #tagFilters {{ display:flex; flex-wrap:wrap; gap:8px; margin-bottom:20px }}
  button.tag {{
    font-family:var(--mono); font-size:10px; letter-spacing:.1em; text-transform:uppercase;
    border:1px solid var(--hairline); border-radius:999px; padding:2px 10px;
    background:var(--surface); color:var(--ink-soft); cursor:pointer;
  }}
  button.tag:hover {{ border-color:var(--accent); color:var(--accent) }}
  button.tag.active {{ background:var(--accent); border-color:var(--accent); color:#fff }}
  button.tag:focus-visible {{ outline:none; box-shadow:0 0 0 2px var(--bg),0 0 0 4px var(--accent) }}
  li.tool .tag {{ cursor:pointer }}
  li.tool .tag:hover {{ border-color:var(--accent); color:var(--accent) }}
  ul.tools {{ list-style:none }}
  li.tool {{ border:1px solid var(--hairline); border-radius:8px; padding:14px 18px; margin-bottom:12px; background:var(--surface) }}
  li.tool h2 {{ font-size:15px; font-weight:650 }}
  li.tool h2 a {{ color:var(--ink); text-decoration:none }}
  li.tool h2 a:hover {{ color:var(--accent); text-decoration:underline }}
  li.tool .desc {{ color:var(--ink-soft); margin:4px 0 8px }}
  li.tool .meta {{ display:flex; flex-wrap:wrap; gap:8px; align-items:center; font-family:var(--mono); font-size:10px; letter-spacing:.1em; text-transform:uppercase; color:var(--ink-soft) }}
  li.tool .tag {{ border:1px solid var(--hairline); border-radius:999px; padding:1px 8px }}
  #empty {{ color:var(--ink-soft); display:none; padding:24px 0 }}
  footer {{ max-width:720px; margin:0 auto; padding:24px; font-family:var(--mono); font-size:10px; letter-spacing:.1em; text-transform:uppercase; color:var(--ink-soft) }}
  footer a {{ color:var(--ink-soft) }}
</style>
</head>
<body>
<header>
  <h1>tools</h1>
  <span class="count">{count} tool{s}</span>
  <input id="search" type="search" placeholder="Search tools (&ldquo;/&rdquo; to focus)" aria-label="Search tools">
</header>
<main>
  <p class="intro">An assortment of handy little tools, built mostly with the help of LLMs.
  Everything runs client-side in your browser.</p>
  <div id="tagFilters" role="group" aria-label="Filter by tag">{tag_filters}</div>
  <ul class="tools" id="toolList">
{items}
  </ul>
  <p id="empty">No tools match your search.</p>
</main>
<footer>
  <span>generated by build.py &middot; <a href="https://github.com/MrPike/tools">source on github</a></span>
</footer>
<script>
(function () {{
  var input = document.getElementById("search");
  var items = Array.prototype.slice.call(document.querySelectorAll("li.tool"));
  var empty = document.getElementById("empty");
  var activeTags = {{}};

  function filter() {{
    var q = input.value.trim().toLowerCase();
    var wanted = Object.keys(activeTags);
    var shown = 0;
    items.forEach(function (li) {{
      var haystack = li.getAttribute("data-search");
      var toolTags = li.getAttribute("data-tags").split(" ").filter(Boolean);
      var match = !q || haystack.indexOf(q) !== -1;
      if (match) {{
        for (var i = 0; i < wanted.length; i++) {{
          if (toolTags.indexOf(wanted[i]) === -1) {{ match = false; break; }}
        }}
      }}
      li.style.display = match ? "" : "none";
      if (match) shown++;
    }});
    empty.style.display = shown ? "none" : "block";
  }}

  function toggleTag(tag) {{
    if (activeTags[tag]) {{ delete activeTags[tag]; }} else {{ activeTags[tag] = true; }}
    document.querySelectorAll("#tagFilters button.tag").forEach(function (btn) {{
      btn.classList.toggle("active", !!activeTags[btn.getAttribute("data-tag")]);
    }});
    filter();
  }}

  document.querySelectorAll("[data-tag]").forEach(function (el) {{
    el.addEventListener("click", function () {{ toggleTag(el.getAttribute("data-tag")); }});
  }});

  input.addEventListener("input", filter);
  document.addEventListener("keydown", function (e) {{
    if (e.key === "/" && document.activeElement !== input) {{
      e.preventDefault();
      input.focus();
    }}
  }});
}})();
</script>
</body>
</html>
"""

ITEM_TEMPLATE = """    <li class="tool" data-search="{search}" data-tags="{tags_attr}">
      <h2><a href="{slug}/">{title}</a></h2>
      <p class="desc">{description}</p>
      <div class="meta">{created}{tags}</div>
    </li>"""

TAG_FILTER_TEMPLATE = '<button class="tag" data-tag="{tag}">{tag}</button>'


def load_tools():
    tools = []
    for path in sorted(ROOT.iterdir()):
        meta_file = path / "tool.json" if path.is_dir() else None
        if not meta_file or not meta_file.is_file():
            continue
        try:
            meta = json.loads(meta_file.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warning: skipping {meta_file}: {exc}", file=sys.stderr)
            continue
        if "title" not in meta or "description" not in meta:
            print(f"warning: skipping {meta_file}: needs 'title' and 'description'", file=sys.stderr)
            continue
        if not (path / "index.html").is_file():
            print(f"warning: {path.name} has tool.json but no index.html", file=sys.stderr)
        meta["slug"] = path.name
        tools.append(meta)
    # Newest first; tools without a date sink to the bottom.
    tools.sort(key=lambda m: m.get("created", ""), reverse=True)
    return tools


def render_item(meta):
    created = meta.get("created", "")
    created_html = f"<span>{html.escape(created)}</span>" if created else ""
    tags = [str(tag) for tag in meta.get("tags", [])]
    tags_html = "".join(
        f'<button class="tag" data-tag="{html.escape(tag, quote=True)}">{html.escape(tag)}</button>'
        for tag in tags
    )
    # Search covers title, description and tags.
    search_text = " ".join([meta["title"], meta["description"], *tags]).lower()
    return ITEM_TEMPLATE.format(
        slug=html.escape(meta["slug"], quote=True),
        title=html.escape(meta["title"]),
        description=html.escape(meta["description"]),
        created=created_html,
        tags=tags_html,
        search=html.escape(search_text, quote=True),
        tags_attr=html.escape(" ".join(tags), quote=True),
    )


def render_tag_filters(tools):
    tags = sorted({str(tag) for meta in tools for tag in meta.get("tags", [])})
    return "\n".join(
        TAG_FILTER_TEMPLATE.format(tag=html.escape(tag, quote=True)) for tag in tags
    )


def main():
    tools = load_tools()
    page = TEMPLATE.format(
        count=len(tools),
        s="" if len(tools) == 1 else "s",
        tag_filters=render_tag_filters(tools),
        items="\n".join(render_item(m) for m in tools),
    )
    OUTPUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUTPUT.name} listing {len(tools)} tool(s)")


if __name__ == "__main__":
    main()
